[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/users/*"
  to = "https://nodejs304.dszcbaross.edu.hu/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cart/*"
  to = "https://nodejs304.dszcbaross.edu.hu/cart/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/products/*"
  to = "https://nodejs304.dszcbaross.edu.hu/products/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/categories/*"
  to = "https://nodejs304.dszcbaross.edu.hu/categories/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/orders/*"
  to = "https://nodejs304.dszcbaross.edu.hu/orders/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200